### ISSUE TITLE
你好，我是6650xt，使用nootrx时发现有电流声

### ISSUE THREAD

**Issue by june5910aaaa** [00x0A/OC-EFI-Z690AProWifi-DDR4-RX6700XT#1]
Hello, my device is 12490f, 6650xt.

I noticed in the Q&A on the nootrx page that you are also experiencing issues with the sound of graphics card current.

I see that you have resolved the issue of GPU current sound by changing the value to 1 in info.plist.

I would like to ask you how to modify this value. I have downloaded the nootrx source code, but I am not sure which value should be modified in info.plist. Do I still need to compile it after the modification?

Looking forward to your reply, thank you very much. Wishing you a happy life

 
你好，我的设备是12490f，6650xt。
在nootrx页面的问答中发现了你同样也遇到显卡电流声的问题。
看到你们在info.plist中将value修改为1，已经解决了gpu电流声的问题。
我想向你请教下如何修改这个value呢,我下载了nootrx源码，但是不太清楚应该修改info.plist中的哪个value，请问修改后还需要编译吗？
期待你的答复，万分感谢。祝生活愉快，谢谢啦

**Comment by 00x0A** [comment]
1. Open NootRX.kext as a folder
2. Go to content/info.plist and edit as text
3. CTRL/CMD + F to find `<key>PP_WorkLoadPolicyMask</key>` and change value under it to `<integer>1</integer>`, by default it's `<integer>16</integer>`
4. Enjoy a fanless experience of macOS

**Comment by 00x0A** [comment]
If you find this thread again try changing it to 20 for better performance!
